name: CICD DEV
on:
  push:
    branches: DEV
jobs:
    build:
       runs-on: DEVRunner
       steps:
        - name: checkout code
          uses: actions/checkout@v3

        - name: Setup dotnet
          uses: actions/setup-dotnet@v3

        - name: Deploy
          working-directory: C:\actions-runner\_work\TestWeb\TestWeb 
          run: dotnet publish --self-contained -r win-x64 -c Release
